version: '3'
services:
    webapp:
        build:    
            context: ./client/
        volumes:
            - ./client/dist:/var/www/
            - ./client/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8080:80
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80
