version: '3'
services:
    pg_db:
        image: postgres
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5432"]
            interval: 30s
            timeout: 10s
            retries: 5

        volumes:
            - ./schema/:/docker-entrypoint-initdb.d
        restart: always
        environment:
            POSTGRES_DB: db
            POSTGRES_PASSWORD: pass 
            POSTGRES_USER: user
    client:
        build: ./client/
        ports:
            - "8080:80"
    api:
        build: ./api/
        environment:
            DATABASE_URL: postgres://user:pass@pg_db:5432/db
        ports:
            - "3000:3000"
        links:
            - pg_db
        depends_on:
            - pg_db
        restart: on-failure

