version: '3'
services:
    client:
        image: nginx
        volumes:
            - ./client/dist/:/usr/share/nginx/html
        ports:
            - "8080:80"
    api:
        build: ./api/
        environment:
            DATABASE_URL: postgres://user:pass@pg_db:5432/db
        ports:
            - "3000:3000"
        links:
            - pg_db
        depends_on:
            - pg_db
    pg_db:
        image: postgres
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_DB: db
            POSTGRES_PASSWORD: pass 
            POSTGRES_USER: user

